### PR TITLE
Update to allow native Apple Silicon

### PR DESCRIPTION
**Pull request by olejnjak**
This addresses #12, requires dependencies update and deployment target update, since now ARM64 simulator exclude should not be required

### CODE REVIEW

**Comment by nidhik** [comment]
Hi @olejnjak! Thank you for bringing this to our attention. The reason we excluded the arm64 architecture for simulator initially was because the Google IMA SDK did not support it. Since then, it looks as though [M1 support was released](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/history) in v3.16.3 on 4/19/2022. I am trying to confirm if the Google IMA tvOS SDK also supports the M1. If so, we will be able to drop our exclusion. Thank you for your patience and we will have an update for you soon!

**Comment by olejnjak** [comment]
Hellow @nidhik thanks for response, it's been two weeks, any news? :-)

**Comment by nidhik** [comment]
Hi @olejnjak! Sorry for the delay on this. I have been testing using my branch here: https://github.com/muxinc/mux-stats-google-ima/pull/14. But for some reason, the Example is still not building on the M1 mac. It continues to fail with the following, implying that the arm64 architecture for the simulator is not present. 
```
ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/echong/mux-repos/mux-stats-google-ima/Example/Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds' for architecture arm64
```

When you tested out your fork, were you able to run on an M1 simulator? Did you have to do anything additional besides removing the exclusions in the podspec?

**Comment by olejnjak** [comment]
Well your branch does not have updated pods, it still uses Google IMA 3.13.0, according to your Podfile.lock
https://github.com/muxinc/mux-stats-google-ima/blob/961f90bea4f51ad89e1454fad6430b0440b29d2f/Example/Podfile.lock#L3

**Comment by nidhik** [comment]
@olejnjak you're totally right, once I pulled in v3.16.3 the build worked. Working through the Apple TV test next

**Comment by nidhik** [comment]
@olejnjak it doesn't look like the Google IMA tvOS SDK has been updated to support the M1 macs. We pulled in the latest v4.6.1 and it was still a `.framework` (rather than a `.xcframework`) and building it resulted in an error about trying to pull in a dylib built for the device rather than the tvOS simulator. 


So I think I'll remove the exclusion for iOS and keep it for tvOS. Does that sound good to you?

**Comment by olejnjak** [comment]
Yes.

**Comment by nidhik** [comment]
This was released in v0.8.0

**Pull request closed without merging**
